version: '3.1'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-youapp
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MONGO_INITDB_DATABASE: ${DB_DATABASE:-your_database_name}
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
