version: '3.1'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-youapp
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: yourusername
    #   MONGO_INITDB_ROOT_PASSWORD: yourpassword
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
